Elangosurya1998/Religio

- backend/app/Http/Controllers/RegisterController.php
- backend/app/Models/User.php
- backend/composer.json
- backend/composer.lock
- backend/database/migrations/2014_10_12_000000_create_users_table.php
- backend/routes/api.php
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/dashboard/includes/Navbar.js
- frontend/src/landing/includes/Header.js
- frontend/src/landing/includes/LoginHeader.js
- frontend/src/login/forms/Login.js
- frontend/src/login/forms/Register.js
- frontend/src/login/forms/private.js
1.Login Form implementation
2.Registration Form Implementation
3.Logout Functionality Implementation
> Auth Implementation

- backend/app/Http/Controllers/ClientregistrationController.php
- backend/app/Http/Controllers/ProvinceController.php
- backend/app/Models/Clientregistration.php
- backend/app/Models/Province.php
- backend/composer.lock
- backend/database/migrations/2023_04_14_133804_create_provinces_table.php
- backend/database/migrations/2023_04_14_134513_create_client_registrations_table.php
- backend/routes/api.php
- frontend/src/App.js
- frontend/src/dashboard/ClientregistrationAdd.js
- frontend/src/dashboard/ClientregistrationEdit.js
- frontend/src/dashboard/CongregationListlayout.js
- frontend/src/dashboard/Congregationaddlayout.js
- frontend/src/dashboard/Congregationeditlayout.js
- frontend/src/dashboard/Provinceaddlayout.js
- frontend/src/dashboard/Provinceeditlayout.js
- frontend/src/dashboard/Provincelistlayout.js
- frontend/src/dashboard/includes/Main.js
- frontend/src/dashboard/includes/Sidemenubar.js
- frontend/src/dashboard/pages/Api/Api.js
- frontend/src/dashboard/pages/Congregation/CongregationCreate.js
- frontend/src/dashboard/pages/Congregation/CongregationEdit.js
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Province/ProvinceCreate.js
- frontend/src/dashboard/pages/Province/ProvinceEdit.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationEdit.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
- frontend/src/dashboard/registerationlayout.js
1.implement three forms edit ,add, delete method.
2. migration file ,models and  controllers in backend .
> #crud operation for all forms

- backend/app/Http/Controllers/ProvinceController.php
- frontend/src/dashboard/pages/Congregation/CongregationCreate.js
- frontend/src/dashboard/pages/Congregation/CongregationEdit.js
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Province/ProvinceCreate.js
- frontend/src/dashboard/pages/Province/ProvinceEdit.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationEdit.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
1.implement the condition for success messages
> implement the condition for success messages

- backend/app/Http/Controllers/ProvinceController.php
- backend/app/Http/Controllers/ReligioController.php
- backend/app/Models/Province.php
- backend/database/migrations/2023_04_14_133804_create_provinces_table.php
- backend/routes/api.php
- frontend/package-lock.json
- frontend/src/dashboard/pages/Congregation/CongregationCreate.js
- frontend/src/dashboard/pages/Congregation/CongregationEdit.js
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/dashboard/pages/Province/ProvinceCreate.js
- frontend/src/dashboard/pages/Province/ProvinceEdit.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/Province/ProvinceView.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationEdit.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationView.js
1. implement the province and edit the sucess message  message
> implement the province details

- frontend/package-lock.json
- frontend/src/App.js
- frontend/src/dashboard/includes/Navbar.js
- frontend/src/dashboard/includes/Sidemenubar.js
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/dashboard/pages/Payments/PaymentCreate.js
- frontend/src/dashboard/pages/Payments/PaymentList.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/UsersList/ReguserCreate.js
- frontend/src/dashboard/pages/UsersList/ReguserEdit.js
- frontend/src/dashboard/pages/UsersList/ReguserList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
- frontend/src/login/forms/Login.js
- frontend/src/login/forms/User.js
- frontend/src/login/forms/private.js
1. Implement Session Storage
2. Restrict Access for Users
> Session Storage

- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationEdit.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationView.js
> table responsive client regiatration

- backend/app/Http/Controllers/ProvinceController.php
- frontend/package-lock.json
- frontend/package.json
- frontend/public/dashboard/assets/css/style.css
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/dashboard/pages/Province/ProvinceCreate.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
> table dynamic and dasboard data show

- backend/app/Http/Controllers/PaymentController.php
- backend/app/Models/Payment.php
- backend/routes/api.php
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/dashboard/pages/Payments/PaymentCreate.js
- frontend/src/dashboard/pages/Payments/PaymentList.js
- frontend/src/dashboard/pages/Payments/paymentEdit.js
- frontend/src/dashboard/pages/Payments/paymentView.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
1. payment and dynamic table page
> implement the payment page

- backend/app/Http/Controllers/ProvinceController.php
- frontend/src/dashboard/includes/Navbar.js
1. Month Year Groupby
2. Dashboard Filters
> Dashboard-FIlters-Groupby-Month-and-Year

- backend/app/Http/Controllers/ReligioController.php
- backend/routes/api.php
- frontend/src/App.js
- frontend/src/dashboard/includes/Navbar.js
- frontend/src/dashboard/pages/Notification/Notification.js
- frontend/src/dashboard/pages/Notification/NotificationLayout.js
implement notification in dashboard
> Notification for amc

- frontend/src/dashboard/pages/Tab/TabList.js
> Date format change

- frontend/public/index.html
- frontend/public/landing/assets/css/style.css
- frontend/src/dashboard/includes/Footer.js
- frontend/src/dashboard/includes/Main.js
- frontend/src/dashboard/includes/Navbar.js
- frontend/src/dashboard/includes/Sidemenubar.js
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/landing/ScrollToTop.js
- frontend/src/landing/includes/Footer.js
- frontend/src/landing/includes/Main.js
Closes #64
1. Responsive menu bar
2. Responsive tabs
> Dashboard Responsive Fix

- backend/app/Http/Controllers/ProvinceController.php
- backend/app/Http/Controllers/ReligioController.php
- backend/routes/api.php
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/dashboard/pages/Notification/Notification.js
1.implement the filter options
2. add clients and filter based on the month and year
> implement the filter options

- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalCreate.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalEdit.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalList.js
> implement domain module

- backend/app/Http/Controllers/DomainrenewalController.php
- backend/routes/api.php
- frontend/src/App.js
- frontend/src/dashboard/pages/Domainrenewal/DomainrenewalLayouts.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalCreate.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalEdit.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalList.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalView.js
> implement-domain-crud

- backend/app/Http/Controllers/RegisterController.php
- backend/app/Mail/Domain.php
- backend/resources/views/mail/domain.blade.php
- backend/routes/api.php
- frontend/src/dashboard/pages/Dashboard.js
> domain send mail

- backend/app/Http/Controllers/ProvinceController.php
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalList.js
- frontend/src/dashboard/pages/Payments/PaymentList.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/UsersList/ReguserList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
1. fixed that amc issue in dasboard page.
2. changed the icons in all list page.
> fixing the dashboard filter for amc amc

- backend/app/Http/Controllers/ProvinceController.php
implement the orderBy in finalcial year
> implement the orderBy in finalcialyear

- frontend/public/landing/assets/css/style.css
- frontend/src/dashboard/pages/Congregation/CongregationList.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalCreate.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalList.js
- frontend/src/dashboard/pages/Ourclientsay/includes/OurclientList.js
- frontend/src/dashboard/pages/OurcustomerSay/includes/OurCustomerSayList.js
- frontend/src/dashboard/pages/Payments/PaymentList.js
- frontend/src/dashboard/pages/Province/ProvinceList.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationEdit.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationList.js
> change the validation for datepicker

- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalCreate.js
- frontend/src/dashboard/pages/Domainrenewal/includes/DomainrenewalEdit.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationCreate.js
- frontend/src/dashboard/pages/clientregistration/clientregistrationEdit.js
> add datepicker icons

- backend/app/Http/Controllers/PaymentController.php
- backend/app/Http/Controllers/ProvinceController.php
- backend/app/Http/Controllers/ReligioController.php
- backend/routes/api.php
- frontend/src/App.js
- frontend/src/dashboard/includes/Navbar.js
- frontend/src/dashboard/pages/Dashboard.js
- frontend/src/dashboard/pages/Notification/Outstanding.js
- frontend/src/dashboard/pages/Notification/OutstandingLayout.js
- frontend/src/dashboard/pages/Payments/PaymentList.js
> change the count in dashboard

- backend/app/Http/Controllers/ProjectsController.php
- backend/app/Http/Controllers/ReligioController.php
- frontend/src/dashboard/pages/Notification/Notification.js
- frontend/src/dashboard/pages/Notification/Outstanding.js
- frontend/src/dashboard/pages/Tab/TabList.js
> implement the total counts

- frontend/src/dashboard/pages/Payments/PaymentList.js
> status update for payment
